# Generated by Django 4.2.4 on 2023-09-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0002_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
