# Generated by Django 4.2.4 on 2023-09-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='id',
            new_name='ids',
        ),
    ]
