# Generated by Django 4.2.4 on 2023-09-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
    ]
